env:
  es2021: true
  node: true
extends:
  - airbnb-base
  - plugin:jest/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
  - jest
rules:
  import/extensions: off
  import/no-unresolved: off
  import/prefer-default-export: off
  no-console: 0
  class-methods-use-this: 0
